name: "Build All"

runs:
  using: "composite"
  steps:
    - name: Refresh dependencies
      run: sudo apt update
    - name: Install dependencies
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq --no-install-recommends build-essential debhelper dh-python dpkg-dev python3 python3-distutils-extra po-debconf pyflakes3 lsb-release gnu-efi
    - name: Build package
      run: dpkg-buildpackage --no-sign
