name: release
on:
  push:
    tags:
      - '*'

jobs:
  linux:
    name: ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Reuse main workflow for artifacts
        uses: ./.github/workflows/main.yml
      - name: Upload artifacts to release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ../dell-recovery*.deb
          draft: true
          generate_release_notes: true
